### ISSUE TITLE
Fails to complete build

### ISSUE THREAD

**Issue by legrande32605** [turboapps/powershell-builds#2]
I've run this package a couple of times on clean VM.  It times out after posting the "Waiting for .xapple file to be created..." message in the console.
[Capture_20240220_105829.log](https://github.com/turboapps/powershell-builds/files/14350104/Capture_20240220_105829.log)
[log-2024-02-20T10.58.20.2334304-08.00.log](https://github.com/turboapps/powershell-builds/files/14350105/log-2024-02-20T10.58.20.2334304-08.00.log)

**Comment by legrande32605** [comment]
forgot to mention.  This on on the R-Project_R package.

**Comment by legrande32605** [comment]
In the r-project_r\4.3.2\TurboCapture\Files\Default\@APPDATALOCAL@\  folder there is just the folders of Programs\Common\.  There are no files in these folders.

I ran the TurboImageBuilder.hta program again this morning on a clean reset VM.  I am logged in as the local admin ran the .hta as administrator to rule out permission issues.  I am currently about 30 minutes into the 60 minute check for the .xapple file.  It does not seem to be progressing.

**Comment by olegsomphane** [comment]
@legrande32605, apologies for the confusion - the %LOCALAPPDATA%\Turbo\Logs folder will be outside of the output folder for the application capture/build script. It will contain logs from Turbo Studio and Client.

However, no worries, our engineers were able to identify the issue from the traces from the attached Capture logs and have put in a fix to resolve the issue.

You may try the fix using the test (not for production) build of Turbo Studio at my OneDrive link below:
https://turbohq-my.sharepoint.com/:u:/g/personal/oleg_turbo_net/EVEC9bT9sOFFpnV_Sz9WT1cB2vKLtgWfjZ8vEkop5P69Sw?e=1P5Dyb

Once the fix completes review and test validation, it will be available in the next official release of Turbo Studio.

**Comment by olegsomphane** [comment]
This issue has been resolved in Turbo Studio 24.2.6.302.
https://start-c.turbo.net/layers/turbo/studio/Download/turbo-studio-24.2.6.302.msi
